### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by bernardolins**
- [x] Support Cowboy 2.0
- [x] Improve error validation
- [x] Add `FakeServer.start` to improve standalone server support 
- [x] Move FakeServer.HTTP.Response to FakeServer.Response
- [x] Rename `code` to `status` on `Response` struct to keep the standard with most libraries
- [x] Add both `{:ok, _} | {:error, _}` and raise options to API
- [x] Add `%FakeServer.Route{}` struct to manage routes and responses
- [x] Split handlers into response types
- [x] Remove `FakeControllers`

### CODE REVIEW

**Comment by kevinbader** [comment]
Hi, thanks for keeping up the good work, highly appreciated! I'm playing around with this branch, mainly because I need cowboy 2, but I can't seem to get it working. Is this broken?

```elixir
defmodule MyFakeServerTest do
  @moduledoc false
  use ExUnit.Case, async: false

  import FakeServer
  alias FakeServer.HTTP.Response

  test_with_server "setting up a route works as expected" do
    route("/foo", do: Response.ok(~s<{"status":"ok"}>))
  end
end
```

When run with `mix test` this yields:

```plain
== Compilation error in file test/my_fake_server_test.exs ==
** (CompileError) test/my_fake_server_test.exs:9: FakeServer.Env.__struct__/0 is undefined, cannot expand struct FakeServer.Env
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (fake_server) expanding macro: FakeServer.route/2
    test/my_fake_server_test.exs:9: MyFakeServerTest."test setting up a route works as expected"/1
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by bernardolins** [comment]
Hello @kevinbader, thanks for the feedback! I am taking the opportunity to improve the code and refactor some modules and the `FakeServer.Env` module was removed. I will fix this to ensure the code in this branch compiles while 2.0.0 version is not released. Just take care, because version 2.X will not be fully compatible with 1.X (For example, FakeControllers were removed).  Please, tell me if you have any trouble.

**Comment by kevinbader** [comment]
Hi @bernardolins, thanks a lot for the quick fix! Finally had the chance to try this and it works just fine :)

Here's my test code, for reference:

```elixir
defmodule MyFakeServerTest do
  @moduledoc false
  use ExUnit.Case, async: false

  import FakeServer
  alias FakeServer.Response

  alias HTTPoison

  test_with_server "setting up a route works as expected" do
    %{port: port} = FakeServer.http_address() |> URI.parse()
    route("/foo", Response.ok!("Hello from port #{port}"))
    assert %HTTPoison.Response{status_code: 200} = HTTPoison.get!("http://localhost:#{port}/foo")
  end
end
```

**Comment by kevinbader** [comment]
btw, perhaps that's gonna be changed anyway, but just to document it here: the request object now keeps the parsed query map in `query_string` instead of `query`, e.g.:

```elixir
%FakeServer.Request{
  body: nil,
  cookies: %{},
  headers: %{"host" => "localhost:4000", "user-agent" => "hackney/1.14.3"},
  method: "GET",
  path: "/my-endpoint",
  query: %{},
  query_string: %{"foo" => "bar"}
}
```

**Comment by bernardolins** [comment]
> btw, perhaps that's gonna be changed anyway, but just to document it here: the request object now keeps the parsed query map in `query_string` instead of `query`, e.g.:
> 
> ```elixir
> %FakeServer.Request{
>   body: nil,
>   cookies: %{},
>   headers: %{"host" => "localhost:4000", "user-agent" => "hackney/1.14.3"},
>   method: "GET",
>   path: "/my-endpoint",
>   query: %{},
>   query_string: %{"foo" => "bar"}
> }
> ```

Hum, nice catch. This is a mistake, the `query_string` field should be a string and not a map. The map should be available at the `query` field.

**Pull request merged**
