### PR TITLE
Add support for response headers

### PR DESCRIPTION
**Pull request by vidmantas**
Implements #15 

There're several questions I'm not very certain about: 
- how to test cowboy request params correctly in `test/fake_server/handler_test.exs`. Now I did it with simple param matching.
- how come that 
```elixir
def create(name, status = %{response_code: _code, response_body: _body}) do
```
pattern matches status with `response_headers` as well? 

Any help appreciated ;)

### CODE REVIEW

**Comment by bernardolins** [comment]
Hi @vidmantas, thanks for your contribution! :)

> how to test cowboy request params correctly in test/fake_server/handler_test.exs. Now I did it with simple param matching.

I can't see a better way to test cowboy request params since `cowboy_req.reply` requires a valid `conn` parameter, which is a very complex tuple. I made this kind of validation myself in the rest of test file. In the future, I think this could be improved but looks good for now. 

> how come that def create(name, status = %{response_code: _code, response_body: _body}) do pattern matches status with response_headers as well?

Cowboy needs the response headers to be a tuple array; otherwise, it will throw an error. But headers must be optional param on `FakeServer.Status.create`. You could do something like this to make sure cowboy won't complain about the headers when the user doesn't provide them:
```elixir
def create(name, status = %{response_code: _code, response_body: _body,  response_headers: _headers}) do
  # Cowboy requires the headers to be a tuple list, so we need to convert the headers map.
  # I think the map syntax is cleaner than a tuple list, but this is just a preference.
  status = Map.update!(status, :response_headers, &(Map.to_list/1)) 
  # the rest if the body of create function
  # .....
end
# If the Status is created without headers, we call the create function with empty headers
def create(name, status = %{response_code: code, response_body: body}) do 
  create(name, %{response_code: code, response_body: body, response_headers:%{}])
end
```

The PR looks good to me. Please, just add some conversion from a map to a tuple list, like the one I show, and I'll be glad to accept. And if you need any more assistance I'll be glad to help. Suggestions are welcome either :)

**Comment by vidmantas** [comment]
@bernardolins thanks for suggestions! I've added additional commit with your suggested changes (I'll squash them when you confirm it's all fine)

The last (I think) hand of help is needed for the unused variable warning:

```
warning: variable response_headers is unused
  test/fake_server/handler_test.exs:37

warning: variable response_headers is unused
  test/fake_server/handler_test.exs:38
```

Test case itself:
```elixir
test "#handle passes correct status code, body and headers to cowboy to reply with" do
    FakeServer.Behavior.create(:behavior, [:status_200])
    response_headers = Map.to_list(@response_headers) # line 37
    with_mock :cowboy_req, [reply: fn(@response_code, response_headers, @response_body, _) -> {:ok, :replied}  end] do
      assert FakeServer.Handler.handle(@conn, @valid_opts) == {:ok, @conn, @valid_opts}
    end
    FakeServer.Behavior.destroy(:behavior)
  end
```

As you can see it is actually used for pattern matching, I don't quite get why it complains. Any ideas?

**Comment by bernardolins** [comment]
I think that's because you are not using it inside `with_mock` block. Since you don't need it to create the mock, you can just ignore this variable adding an underscore where it appears.

The code looks good to me, you can squash the commits and I'll be glad to accept the PR.

One more time, thank you for your contribution. If you have any more questions feel free to ask :)

**Comment by vidmantas** [comment]
Squashed, thanks a lot for your help!

**Pull request merged**
